#!/bin/sh

set +e
cp -n "/usr/local/bin/LiberaBrilliancePlus/LiberaBrilliancePlus.sh" "/etc/init.d/LiberaBrilliancePlus"

set -e
chmod 751 /usr/local/bin/LiberaBrilliancePlus/LiberaBrilliancePlus
chmod 751 /usr/local/bin/LiberaBrilliancePlus/configure.sh
chmod 751 /etc/init.d/LiberaBrilliancePlus

touch "/var/log/LiberaBrilliancePlus.log" && chown "root" "/var/log/LiberaBrilliancePlus.log"

if [ "x$TANGO_HOST" != "x" ] && [ "x$TANGO_INSTANCE" != "x" ]; then
    sed -i "s/TANGO_HOST_PLACEHOLDER/$TANGO_HOST/g" /etc/init.d/LiberaBrilliancePlus
    sed -i "s/TANGO_INSTANCE_PLACEHOLDER/$TANGO_INSTANCE/g" /etc/init.d/LiberaBrilliancePlus
fi

update-rc.d "LiberaBrilliancePlus" defaults 99

service "LiberaBrilliancePlus" start
