/*----- PROTECTED REGION ID(LiberaBrilliancePlusStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LiberaBrilliancePlusStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     Libera BPM Device Server.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <LiberaBrilliancePlus.h>
#include <LiberaBrilliancePlusClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * LiberaBrilliancePlus states description:
 *
 * UNKNOWN :	Device is not [or not properly] initialized 
 * FAULT :	Device initialization failed or unrecoverable error 
 * ON :	BPM is up and running 
 */

namespace LiberaBrilliancePlus_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_LiberaModelState_allowed()
 *	Description : Execution allowed for LiberaModel attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_LiberaModel_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for LiberaModel attribute in READ access.
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_LiberaModelStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_LiberaModelStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDEnabledState_allowed()
 *	Description : Execution allowed for DDEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDEnabled_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for DDEnabled attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DDEnabledStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DDEnabledStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDBufferSizeState_allowed()
 *	Description : Execution allowed for DDBufferSize attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDBufferSize_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for DDBufferSize attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DDBufferSizeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DDBufferSizeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDBufferSizeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDBufferSizeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDDecimationFactorState_allowed()
 *	Description : Execution allowed for DDDecimationFactor attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDDecimationFactor_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for DDDecimationFactor attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DDDecimationFactorStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DDDecimationFactorStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDDecimationFactorStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDDecimationFactorStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDTriggerOffsetState_allowed()
 *	Description : Execution allowed for DDTriggerOffset attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDTriggerOffset_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for DDTriggerOffset attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DDTriggerOffsetStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DDTriggerOffsetStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDTriggerOffsetStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDTriggerOffsetStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDBufferFreezingEnabledState_allowed()
 *	Description : Execution allowed for DDBufferFreezingEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDBufferFreezingEnabled_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDBufferFreezingEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDBufferFreezingEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDBufferFrozenState_allowed()
 *	Description : Execution allowed for DDBufferFrozen attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDBufferFrozen_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDBufferFrozenStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDBufferFrozenStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DDTriggerCounterState_allowed()
 *	Description : Execution allowed for DDTriggerCounter attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DDTriggerCounter_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DDTriggerCounterStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DDTriggerCounterStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ExternalTriggerEnabledState_allowed()
 *	Description : Execution allowed for ExternalTriggerEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ExternalTriggerEnabled_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ExternalTriggerEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ExternalTriggerEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ExternalTriggerDelayState_allowed()
 *	Description : Execution allowed for ExternalTriggerDelay attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ExternalTriggerDelay_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for ExternalTriggerDelay attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ExternalTriggerDelayStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ExternalTriggerDelayStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ExternalTriggerDelayStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ExternalTriggerDelayStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SAEnabledState_allowed()
 *	Description : Execution allowed for SAEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SAEnabled_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for SAEnabled attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SAEnabledStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SAEnabledStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SAEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SAEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VaSAState_allowed()
 *	Description : Execution allowed for VaSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VaSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VaSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VaSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VbSAState_allowed()
 *	Description : Execution allowed for VbSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VbSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VbSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VbSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VcSAState_allowed()
 *	Description : Execution allowed for VcSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VcSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VcSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VcSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VdSAState_allowed()
 *	Description : Execution allowed for VdSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VdSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VdSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VdSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XPosSAState_allowed()
 *	Description : Execution allowed for XPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZPosSAState_allowed()
 *	Description : Execution allowed for ZPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SumSAState_allowed()
 *	Description : Execution allowed for SumSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SumSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SumSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SumSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QuadSAState_allowed()
 *	Description : Execution allowed for QuadSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QuadSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QuadSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QuadSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_CxSAState_allowed()
 *	Description : Execution allowed for CxSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_CxSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_CxSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_CxSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_CzSAState_allowed()
 *	Description : Execution allowed for CzSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_CzSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_CzSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_CzSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SAStatNumSamplesState_allowed()
 *	Description : Execution allowed for SAStatNumSamples attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SAStatNumSamples_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for SAStatNumSamples attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SAStatNumSamplesStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SAStatNumSamplesStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SAStatNumSamplesStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SAStatNumSamplesStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XMeanPosSAState_allowed()
 *	Description : Execution allowed for XMeanPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XMeanPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XMeanPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XMeanPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZMeanPosSAState_allowed()
 *	Description : Execution allowed for ZMeanPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZMeanPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZMeanPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZMeanPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XRMSPosSAState_allowed()
 *	Description : Execution allowed for XRMSPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XRMSPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XRMSPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XRMSPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZRMSPosSAState_allowed()
 *	Description : Execution allowed for ZRMSPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZRMSPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZRMSPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZRMSPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XPeakPosSAState_allowed()
 *	Description : Execution allowed for XPeakPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XPeakPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XPeakPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XPeakPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZPeakPosSAState_allowed()
 *	Description : Execution allowed for ZPeakPosSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZPeakPosSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZPeakPosSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZPeakPosSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SumMeanSAState_allowed()
 *	Description : Execution allowed for SumMeanSA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SumMeanSA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SumMeanSAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SumMeanSAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCEnabledState_allowed()
 *	Description : Execution allowed for ADCEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCEnabled_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for ADCEnabled attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ADCEnabledStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ADCEnabledStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCBufferSizeState_allowed()
 *	Description : Execution allowed for ADCBufferSize attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCBufferSize_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for ADCBufferSize attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ADCBufferSizeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ADCBufferSizeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCBufferSizeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCBufferSizeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_PMOffsetState_allowed()
 *	Description : Execution allowed for PMOffset attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_PMOffset_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for PMOffset attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::PMOffsetStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::PMOffsetStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_PMOffsetStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_PMOffsetStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_PMNotifiedState_allowed()
 *	Description : Execution allowed for PMNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_PMNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_PMNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_PMNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_PMNotificationCounterState_allowed()
 *	Description : Execution allowed for PMNotificationCounter attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_PMNotificationCounter_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_PMNotificationCounterStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_PMNotificationCounterStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockXNotifiedState_allowed()
 *	Description : Execution allowed for InterlockXNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockXNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockXNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockXNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockZNotifiedState_allowed()
 *	Description : Execution allowed for InterlockZNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockZNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockZNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockZNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockAttnNotifiedState_allowed()
 *	Description : Execution allowed for InterlockAttnNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockAttnNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockAttnNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockAttnNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockADCPreFilterNotifiedState_allowed()
 *	Description : Execution allowed for InterlockADCPreFilterNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockADCPreFilterNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockADCPreFilterNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockADCPreFilterNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockADCPostFilterNotifiedState_allowed()
 *	Description : Execution allowed for InterlockADCPostFilterNotified attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockADCPostFilterNotified_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockADCPostFilterNotifiedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockADCPostFilterNotifiedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XLowState_allowed()
 *	Description : Execution allowed for XLow attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XLow_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XLowStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XLowStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XHighState_allowed()
 *	Description : Execution allowed for XHigh attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XHigh_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XHighStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XHighStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZLowState_allowed()
 *	Description : Execution allowed for ZLow attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZLow_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZLowStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZLowStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZHighState_allowed()
 *	Description : Execution allowed for ZHigh attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZHigh_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZHighStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZHighStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_AutoSwitchingEnabledState_allowed()
 *	Description : Execution allowed for AutoSwitchingEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_AutoSwitchingEnabled_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_AutoSwitchingEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_AutoSwitchingEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SwitchesState_allowed()
 *	Description : Execution allowed for Switches attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_Switches_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Switches attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SwitchesStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SwitchesStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SwitchesStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SwitchesStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ExternalSwitchingState_allowed()
 *	Description : Execution allowed for ExternalSwitching attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ExternalSwitching_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for ExternalSwitching attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ExternalSwitchingStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ExternalSwitchingStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ExternalSwitchingStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ExternalSwitchingStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SwitchingDelayState_allowed()
 *	Description : Execution allowed for SwitchingDelay attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SwitchingDelay_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for SwitchingDelay attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SwitchingDelayStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SwitchingDelayStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SwitchingDelayStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SwitchingDelayStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_OffsetTuneState_allowed()
 *	Description : Execution allowed for OffsetTune attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_OffsetTune_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for OffsetTune attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::OffsetTuneStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::OffsetTuneStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_OffsetTuneStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_OffsetTuneStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_CompensateTuneState_allowed()
 *	Description : Execution allowed for CompensateTune attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_CompensateTune_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for CompensateTune attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::CompensateTuneStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::CompensateTuneStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_CompensateTuneStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_CompensateTuneStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DSCModeState_allowed()
 *	Description : Execution allowed for DSCMode attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DSCMode_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for DSCMode attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DSCModeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DSCModeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_DSCModeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_DSCModeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_AGCEnabledState_allowed()
 *	Description : Execution allowed for AGCEnabled attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_AGCEnabled_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for AGCEnabled attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::AGCEnabledStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::AGCEnabledStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_AGCEnabledStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_AGCEnabledStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_GainState_allowed()
 *	Description : Execution allowed for Gain attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_Gain_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Gain attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::GainStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::GainStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_GainStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_GainStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_HasMAFSupportState_allowed()
 *	Description : Execution allowed for HasMAFSupport attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_HasMAFSupport_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_HasMAFSupportStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_HasMAFSupportStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MAFLengthState_allowed()
 *	Description : Execution allowed for MAFLength attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MAFLength_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for MAFLength attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::MAFLengthStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::MAFLengthStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MAFLengthStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MAFLengthStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MAFDelayState_allowed()
 *	Description : Execution allowed for MAFDelay attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MAFDelay_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for MAFDelay attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::MAFDelayStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::MAFDelayStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MAFDelayStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MAFDelayStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MachineTimeState_allowed()
 *	Description : Execution allowed for MachineTime attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MachineTime_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for MachineTime attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::MachineTimeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::MachineTimeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MachineTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MachineTimeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_TimePhaseState_allowed()
 *	Description : Execution allowed for TimePhase attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_TimePhase_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for TimePhase attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::TimePhaseStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::TimePhaseStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_TimePhaseStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_TimePhaseStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SystemTimeState_allowed()
 *	Description : Execution allowed for SystemTime attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SystemTime_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for SystemTime attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SystemTimeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SystemTimeStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SystemTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SystemTimeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SCPLLStatusState_allowed()
 *	Description : Execution allowed for SCPLLStatus attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SCPLLStatus_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SCPLLStatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SCPLLStatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MCPLLStatusState_allowed()
 *	Description : Execution allowed for MCPLLStatus attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MCPLLStatus_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MCPLLStatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MCPLLStatusStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_HWTemperatureState_allowed()
 *	Description : Execution allowed for HWTemperature attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_HWTemperature_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_HWTemperatureStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_HWTemperatureStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_Fan1SpeedState_allowed()
 *	Description : Execution allowed for Fan1Speed attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_Fan1Speed_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_Fan1SpeedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_Fan1SpeedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_Fan2SpeedState_allowed()
 *	Description : Execution allowed for Fan2Speed attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_Fan2Speed_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_Fan2SpeedStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_Fan2SpeedStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_IncoherenceState_allowed()
 *	Description : Execution allowed for Incoherence attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_Incoherence_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_IncoherenceStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_IncoherenceStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_RefIncoherenceState_allowed()
 *	Description : Execution allowed for RefIncoherence attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_RefIncoherence_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_RefIncoherenceStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_RefIncoherenceStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MaxIncoherenceState_allowed()
 *	Description : Execution allowed for MaxIncoherence attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MaxIncoherence_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for MaxIncoherence attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::MaxIncoherenceStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::MaxIncoherenceStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MaxIncoherenceStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MaxIncoherenceStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_MaxIncoherenceDriftState_allowed()
 *	Description : Execution allowed for MaxIncoherenceDrift attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_MaxIncoherenceDrift_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for MaxIncoherenceDrift attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::MaxIncoherenceDriftStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::MaxIncoherenceDriftStateAllowed_WRITE

		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_MaxIncoherenceDriftStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_MaxIncoherenceDriftStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_UpTimeState_allowed()
 *	Description : Execution allowed for UpTime attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_UpTime_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_UpTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_UpTimeStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_CpuUsageState_allowed()
 *	Description : Execution allowed for CpuUsage attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_CpuUsage_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_CpuUsageStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_CpuUsageStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_FreeMemoryState_allowed()
 *	Description : Execution allowed for FreeMemory attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_FreeMemory_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_FreeMemoryStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_FreeMemoryStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_RamFsUsageState_allowed()
 *	Description : Execution allowed for RamFsUsage attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_RamFsUsage_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_RamFsUsageStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_RamFsUsageStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_UseLiberaSADataState_allowed()
 *	Description : Execution allowed for UseLiberaSAData attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_UseLiberaSAData_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for UseLiberaSAData attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::UseLiberaSADataStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::UseLiberaSADataStateAllowed_WRITE

		return true;
	}
	else
		//	Not any excluded states for UseLiberaSAData attribute in READ access.
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_UseLiberaSADataStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_UseLiberaSADataStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XPosDDState_allowed()
 *	Description : Execution allowed for XPosDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XPosDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XPosDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XPosDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZPosDDState_allowed()
 *	Description : Execution allowed for ZPosDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZPosDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZPosDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZPosDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QuadDDState_allowed()
 *	Description : Execution allowed for QuadDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QuadDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QuadDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QuadDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SumDDState_allowed()
 *	Description : Execution allowed for SumDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SumDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SumDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SumDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VaDDState_allowed()
 *	Description : Execution allowed for VaDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VaDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VaDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VaDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VbDDState_allowed()
 *	Description : Execution allowed for VbDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VbDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VbDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VbDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VcDDState_allowed()
 *	Description : Execution allowed for VcDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VcDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VcDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VcDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VdDDState_allowed()
 *	Description : Execution allowed for VdDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VdDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VdDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VdDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XPosSAHistoryState_allowed()
 *	Description : Execution allowed for XPosSAHistory attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XPosSAHistory_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XPosSAHistoryStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XPosSAHistoryStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZPosSAHistoryState_allowed()
 *	Description : Execution allowed for ZPosSAHistory attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZPosSAHistory_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZPosSAHistoryStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZPosSAHistoryStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SumSAHistoryState_allowed()
 *	Description : Execution allowed for SumSAHistory attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SumSAHistory_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SumSAHistoryStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SumSAHistoryStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_XPosPMState_allowed()
 *	Description : Execution allowed for XPosPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_XPosPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_XPosPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_XPosPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ZPosPMState_allowed()
 *	Description : Execution allowed for ZPosPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ZPosPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ZPosPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ZPosPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QuadPMState_allowed()
 *	Description : Execution allowed for QuadPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QuadPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QuadPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QuadPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SumPMState_allowed()
 *	Description : Execution allowed for SumPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SumPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_SumPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_SumPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VaPMState_allowed()
 *	Description : Execution allowed for VaPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VaPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VaPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VaPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VbPMState_allowed()
 *	Description : Execution allowed for VbPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VbPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VbPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VbPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VcPMState_allowed()
 *	Description : Execution allowed for VcPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VcPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VcPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VcPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_VdPMState_allowed()
 *	Description : Execution allowed for VdPM attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_VdPM_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_VdPMStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_VdPMStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCChannelAState_allowed()
 *	Description : Execution allowed for ADCChannelA attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCChannelA_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCChannelAStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCChannelAStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCChannelBState_allowed()
 *	Description : Execution allowed for ADCChannelB attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCChannelB_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCChannelBStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCChannelBStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCChannelCState_allowed()
 *	Description : Execution allowed for ADCChannelC attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCChannelC_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCChannelCStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCChannelCStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ADCChannelDState_allowed()
 *	Description : Execution allowed for ADCChannelD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ADCChannelD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_ADCChannelDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_ADCChannelDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_IaDDState_allowed()
 *	Description : Execution allowed for IaDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_IaDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_IaDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_IaDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_IbDDState_allowed()
 *	Description : Execution allowed for IbDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_IbDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_IbDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_IbDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_IcDDState_allowed()
 *	Description : Execution allowed for IcDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_IcDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_IcDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_IcDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_IdDDState_allowed()
 *	Description : Execution allowed for IdDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_IdDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_IdDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_IdDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QaDDState_allowed()
 *	Description : Execution allowed for QaDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QaDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QaDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QaDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QbDDState_allowed()
 *	Description : Execution allowed for QbDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QbDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QbDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QbDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QcDDState_allowed()
 *	Description : Execution allowed for QcDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QcDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QcDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QcDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_QdDDState_allowed()
 *	Description : Execution allowed for QdDD attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_QdDD_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_QdDDStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_QdDDStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_UserDataState_allowed()
 *	Description : Execution allowed for UserData attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_UserData_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_UserDataStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_UserDataStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_InterlockConfigurationState_allowed()
 *	Description : Execution allowed for InterlockConfiguration attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_InterlockConfiguration_allowed(Tango::AttReqType type)
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_InterlockConfigurationStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_InterlockConfigurationStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_logsState_allowed()
 *	Description : Execution allowed for logs attribute.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_logs_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for logs attribute in READ access.
	
	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::read_logsStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::read_logsStateAllowed_READ

	return true;
}


	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_GetParametersState_allowed()
 *	Description : Execution allowed for GetParameters command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_GetParameters_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::GetParametersStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::GetParametersStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_UnfreezeDDBufferState_allowed()
 *	Description : Execution allowed for UnfreezeDDBuffer command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_UnfreezeDDBuffer_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::UnfreezeDDBufferStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::UnfreezeDDBufferStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_EnableDDBufferFreezingState_allowed()
 *	Description : Execution allowed for EnableDDBufferFreezing command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_EnableDDBufferFreezing_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::EnableDDBufferFreezingStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::EnableDDBufferFreezingStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DisableDDBufferFreezingState_allowed()
 *	Description : Execution allowed for DisableDDBufferFreezing command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DisableDDBufferFreezing_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DisableDDBufferFreezingStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DisableDDBufferFreezingStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_EnableDDState_allowed()
 *	Description : Execution allowed for EnableDD command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_EnableDD_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::EnableDDStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::EnableDDStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DisableDDState_allowed()
 *	Description : Execution allowed for DisableDD command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DisableDD_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DisableDDStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DisableDDStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_EnableSAState_allowed()
 *	Description : Execution allowed for EnableSA command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_EnableSA_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::EnableSAStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::EnableSAStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DisableSAState_allowed()
 *	Description : Execution allowed for DisableSA command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DisableSA_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DisableSAStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DisableSAStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ResetPMNotificationState_allowed()
 *	Description : Execution allowed for ResetPMNotification command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ResetPMNotification_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ResetPMNotificationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ResetPMNotificationStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ResetInterlockNotificationState_allowed()
 *	Description : Execution allowed for ResetInterlockNotification command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ResetInterlockNotification_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ResetInterlockNotificationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ResetInterlockNotificationStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SetInterlockConfigurationState_allowed()
 *	Description : Execution allowed for SetInterlockConfiguration command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SetInterlockConfiguration_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SetInterlockConfigurationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SetInterlockConfigurationStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_EnableADCState_allowed()
 *	Description : Execution allowed for EnableADC command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_EnableADC_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::EnableADCStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::EnableADCStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_DisableADCState_allowed()
 *	Description : Execution allowed for DisableADC command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_DisableADC_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::DisableADCStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::DisableADCStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SetTimeOnNextTriggerState_allowed()
 *	Description : Execution allowed for SetTimeOnNextTrigger command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SetTimeOnNextTrigger_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SetTimeOnNextTriggerStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SetTimeOnNextTriggerStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ReadFADataState_allowed()
 *	Description : Execution allowed for ReadFAData command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ReadFAData_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ReadFADataStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ReadFADataStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_WriteFADataState_allowed()
 *	Description : Execution allowed for WriteFAData command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_WriteFAData_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::WriteFADataStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::WriteFADataStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SaveDSCParametersState_allowed()
 *	Description : Execution allowed for SaveDSCParameters command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SaveDSCParameters_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SaveDSCParametersStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SaveDSCParametersStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_ReloadSystemPropertiesState_allowed()
 *	Description : Execution allowed for ReloadSystemProperties command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_ReloadSystemProperties_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::ReloadSystemPropertiesStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::ReloadSystemPropertiesStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaBrilliancePlus::is_SetRefIncoherenceState_allowed()
 *	Description : Execution allowed for SetRefIncoherence command.
 */
//--------------------------------------------------------

bool LiberaBrilliancePlus::is_SetRefIncoherence_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::UNKNOWN	|| 
		get_state() == Tango::FAULT)
	{

	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::SetRefIncoherenceStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::SetRefIncoherenceStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(LiberaBrilliancePlus::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::are_dynamic_commands_allowed

}	// namespace LiberaBrilliancePlus_ns
