/*----- PROTECTED REGION ID(LiberaBrilliancePlus.h) ENABLED START -----*/
//=============================================================================
//
// file :        LiberaBrilliancePlus.h
//
// description : Include file for the LiberaBrilliancePlus class
//
// project :     Libera BPM Device Server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef LiberaBrilliancePlus_H
#define LiberaBrilliancePlus_H

#include <tango.h>

class LiberaClient;
class LiberaSignal;

/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus.h

/**
 *  LiberaBrilliancePlus class description:
 *    IT Libera BPM Device Server.
 *    The interface should be the same as for the Brillance model.
 */

namespace LiberaBrilliancePlus_ns
{
/*----- PROTECTED REGION ID(LiberaBrilliancePlus::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::Additional Class Declarations

class LiberaBrilliancePlus : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(LiberaBrilliancePlus::Data Members) ENABLED START -----*/

	//		Add your own data members
    LiberaClient *m_libera;

    LiberaSignal *m_signalDdc;
    LiberaSignal *m_signalDdcRaw;
    Tango::DevBoolean *attr_DDEnabled_read_added; //declared here for completeness
    Tango::DevLong   *attr_DDBufferSize_read_added;

    LiberaSignal *m_signalSA;
    LiberaSignal *m_signalFA;

    LiberaSignal *m_signalPM;
    Tango::DevBoolean *attr_PMEnabled_read_added; //declared here for completeness
    Tango::DevLong   *attr_PMBufferSize_read_added;

    LiberaSignal *m_signalADC;
    //Single Pass Signal
    LiberaSignal *m_signalSP;
    LiberaSignal *m_signalTdp;

    std::string m_raf;

        void DDCallback();
        static void _DDCallback(void *data);
        void SACallback();
        static void _SACallback(void *data);
        void FACallback();
        static void _FACallback(void *data);
        void PMCallback();
        static void _PMCallback(void *data);
        void SPCallback();
        static void _SPCallback(void *data);
        void TDCallback();
        static void _TDCallback(void *data);
        
        bool initFlag;
        void init_settings();

        void LogStatusGuard(std::string status);               // Give the status to Tango.

        Tango::DevState m_state;
        std::string m_status;
        std::string current_status;

	/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::Data Members

//	Device property data members
public:
	//	LiberaIpAddr:	The Libera IP address [no default value]
	string	liberaIpAddr;
	//	LiberaPort:	The port on which the generic server handles external requests. Defaults to 23721.
	Tango::DevShort	liberaPort;
	//	DefaultDDBufferSize:	Default [or initial] value for attribute DDBufferSize [in samples]. Defaults to 1024.
	Tango::DevLong	defaultDDBufferSize;
	//	Switches:	Switches configuration. The valid range is [0..15]. Defaults to 3.
	Tango::DevShort	switches;
	//	LiberaMulticastIpAddr:	Asynch. notifications (e.g. trigger events) will be send to this addr [no default value]
	string	liberaMulticastIpAddr;
	//	Location:	The BPM location [TL1, BOOSTER, TL2 or STORAGE_RING]. No default value.
	string	location;
	//	EnableExternalTrigger:	Enables (or not) the external trigger source.
	//  Inlfuences the TANGO device behaviour not the Libera itself. Defaults to false.
	Tango::DevBoolean	enableExternalTrigger;
	//	DDTaskActivityPeriod:	Specify the watch-dog (1) or data reading period (2) in ms.
	//  Must be in the rangec [500, 25000] ms. Defaults to 1000.
	//  (1) : external trigger enabled - (2) : external trigger disabled.
	Tango::DevULong	dDTaskActivityPeriod;
	//	SATaskActivityPeriod:	Specify the watch-dog (1) or data reading period (2) in ms.
	//  Must be in the range [100, 25000] ms. Defaults to 100.
	Tango::DevULong	sATaskActivityPeriod;
	//	EnableDD:	Specifies whether or not the DD data source should be enabled at startup. Defaults to false.
	Tango::DevBoolean	enableDD;
	//	EnableSA:	Specifies whether or not the SA data source should be enabled at startup. Defaults to false.
	Tango::DevBoolean	enableSA;
	//	SAHistoryLength:	SA history buffer length [in samples]. Defaults to 8196.
	Tango::DevULong	sAHistoryLength;
	//	DDDecimationFactor:	The DD decimation factor.
	//  Allowed values : 1 (no decimation) or 64 (for the so called booster normal mode)
	Tango::DevUShort	dDDecimationFactor;
	//	ConditionSwitchingEnabled:	When set to TRUE, auto-switching is automattically enabled when the SA data source is itself enabled
	Tango::DevBoolean	conditionSwitchingEnabled;
	//	EnableDSCIfAutoSwitchingEnabled:	When set to TRUE, the Digital Signal Conditioning is automattically enabled when the auto-switching is itself enabled
	Tango::DevBoolean	enableDSCIfAutoSwitchingEnabled;
	//	DefaultSAStatNumSamples:	Default number of SA history samples to use form RMS pos. computation.
	//  Defaults to 10 (last second in the SA history).
	Tango::DevULong	defaultSAStatNumSamples;
	//	DefaultADCBufferSize:	Default [or initial] value for attribute ADCBufferSize [in samples]. Defaults to 1000.
	Tango::DevLong	defaultADCBufferSize;
	//	ADCTaskActivityPeriod:	Specifies the data reading period in ms.
	//  Must be in the range [500, 25000] ms. Defaults to 1000.
	Tango::DevULong	aDCTaskActivityPeriod;
	//	EnableADC:	Specifies whether or not the ADC data source should be enabled at startup. Defaults to false.
	Tango::DevBoolean	enableADC;
	//	DefaultTimePhaseValue:	Default value for the machine time phase. Its valid range is [0, RfSfRatio - 1] where
	//  RfSfRatio is a machine dependent system property.
	Tango::DevLong	defaultTimePhaseValue;
	//	InterlockConfiguration:	The user defined interlock configuration. This is the configuration that should be applied on the Libera in case the device `finds`
	//  the Libera in its default startup configuration when it is itself starting up or executing its Init TANGO command. This configuration
	//  can also be applied using the dedicated `SetInterlockConfiguration` expert command.
	//  Parameters mapping:
	//  [0] Interlock : mode - [0]: disabled, [1]: enabled, [3]: enabled with gain dependency
	//  [1] Interlock : threshold : X low in mm
	//  [2] Interlock : threshold : X high in mm
	//  [3] Interlock : threshold : Z low in mm (i.e. Y low in the Libera terminology)
	//  [4] Interlock : threshold : Z high in mm (i.e. Y high in the Libera terminology)
	//  [5] Interlock : overflow limit (ADC threshold)
	//  [6] Interlock : overflow duration (num of overloaded ADC samples before raising intlck)
	//  [7] Interlock : gain limit in dBm  (intlck not active under this limit) - valid range is [-60, 0]
	vector<Tango::DevDouble>	interlockConfiguration;
	//	EnableDDOptionalData:	Enables/Disables  DD optional data (IxDD and QxDD)
	Tango::DevBoolean	enableDDOptionalData;
	//	EnableSAOptionalData:	Enables/disables SA optional Data (currently not used)
	Tango::DevBoolean	enableSAOptionalData;
	//	EnableSAHistoryOptionalData:	Enables/disables SA History optional data (sum history)
	Tango::DevBoolean	enableSAHistoryOptionalData;
	//	EnableADCOptionalData:	Enables/disables ADC optional data (currently not used)
	Tango::DevBoolean	enableADCOptionalData;
	//	Institute:	0: TANGO_INSTITUTE (GENERIC)
	//  1: ALBA
	//  2: ESRF
	//  3: ELETTRA
	//  4: SOLEIL
	Tango::DevShort	institute;
	//	MaxDDBufferSizeWhenDecimationEnabled:	Max. DD buffer size when decimation enabled on DD data source.
	//  Defaults to 10000
	Tango::DevLong	maxDDBufferSizeWhenDecimationEnabled;
	//	PassBBAOffsetsToFPGA:	Controls wether or not the BBA offsets are taken into account when computing the offsets passed to the FPGA process
	Tango::DevBoolean	passBBAOffsetsToFPGA;
	//	FADataCacheRefreshPeriod:	The <FA Data> cache refresh period in msecs.
	//  Defaults to 500 ms (2Hz).
	Tango::DevULong	fADataCacheRefreshPeriod;
	//	LiberaBoard:	BPM board ID within the chassis [raf3,raf4,raf5 or raf6]
	string	liberaBoard;
	//	EnableTDOptionalData:	Enables/Disables  TD optional data (IxTD and QxTD)
	Tango::DevBoolean	enableTDOptionalData;
	//	DefaultTDBufferSize:	Default [or initial] value for attribute TDBufferSize [in samples]. Defaults to 1024.
	Tango::DevLong	defaultTDBufferSize;
	//	EnableTD:	Specifies whether or not the TD data source should be enabled at startup. Defaults to false.
	Tango::DevBoolean	enableTD;
	//	TDTaskActivityPeriod:	Specify the watch-dog (1) or data reading period (2) in ms.
	//  Must be in the rangec [500, 25000] ms. Defaults to 1000.
	//  (1) : external trigger enabled - (2) : external trigger disabled.
	Tango::DevULong	tDTaskActivityPeriod;
	//	TDDecimationFactor:	The DD decimation factor.
	//  Allowed values : 1 (no decimation) or 64 (for the so called booster normal mode)
	Tango::DevUShort	tDDecimationFactor;
	//	MaxTDBufferSizeWhenDecimationEnabled:	Max. TD buffer size when decimation enabled on DD data source.
	//  Defaults to 10000
	Tango::DevLong	maxTDBufferSizeWhenDecimationEnabled;
	//	EnableSP:	Specifies whether or not the Single Pass data source should be enabled at startup. Defaults to false.
	Tango::DevBoolean	enableSP;
	//	PMCapture:	PM functionality capture: Set True to Disable, False to Enable
	Tango::DevBoolean	pMCapture;
	//	PMOffset:	PM Offset
	Tango::DevLong	pMOffset;
	//	DefaultPMBufferSize:	PM buffer capacity
	Tango::DevLong	defaultPMBufferSize;
	//	PMSource:	source of the PM event External,Interlock,Limits
	Tango::DevShort	pMSource;
	//	InterlockLimitXMin:	X interlock min limit
	Tango::DevDouble	interlockLimitXMin;
	//	InterlockLimitYMin:	Y interlock min limit
	Tango::DevDouble	interlockLimitYMin;
	//	InterlockLimitXMax:	X interlock max limit
	Tango::DevDouble	interlockLimitXMax;
	//	InterlockLimitYMax:	Y interlock max limit
	Tango::DevDouble	interlockLimitYMax;
	//	InterlockEnable:	Specifies whether or not the Interlock should be enabled at startup.
	Tango::DevBoolean	interlockEnable;
	//	SPThreshold:	Specifies the threshold for start of calculation (in ADC counts)
	Tango::DevLong	sPThreshold;
	//	SPnBefore:	Specifies the number of samples to take before the threshold (in ADC samples)
	Tango::DevLong	sPnBefore;
	//	SPnAfter:	Specifies the number of samples to take after the threshold (in ADC samples)
	Tango::DevLong	sPnAfter;
	//	ExternalTriggerDelay:	Sets the delay on the external trigger arrival. The delay is set in steps of ADC samples
	Tango::DevLong	externalTriggerDelay;
	//	DSCMode:	
	Tango::DevShort	dSCMode;
	//	InterlockFilterOverflow:	ADC filter overflow
	Tango::DevLong	interlockFilterOverflow;
	//	InterlockFilterPosition:	ADC filter position
	Tango::DevLong	interlockFilterPosition;
	//	KxCoefficient:	Position calculation Kx coefficient
	Tango::DevDouble	kxCoefficient;
	//	KyCoefficient:	Position calculation Ky coefficient
	Tango::DevDouble	kyCoefficient;
	//	Gain:	Power level Gain Control (Set it only when AGC is Disabled)
	Tango::DevDouble	gain;
	//	EnableAGC:	Enables/disables the Automatic Gain Control
	Tango::DevBoolean	enableAGC;
	//	InterlockGainDependent:	Enables / disables gain dependent mode of Interlock operation.
	Tango::DevBoolean	interlockGainDependent;
	//	ErrorTrace:	Trace Error functionality for the Libera, by default is Disabled:
	//   * Value: OutPut ,  TraceLevel
	//  	* Output[0] :  OutPut on Screen = 0
	//  	                         OutPut on File = 0 (﻿/var/tmp/ds.log/LiberaMciTrace.log)
	//  	* TraceLevel[1] : ﻿   Off     = 0,
	//          		      Low     = 1,
	//  		      Med     = 2,
	//  		      High    = 3,
	//  		      Detail  = 4
	vector<Tango::DevShort>	errorTrace;
	//	InterlockOverflowDuration:	Duration of allowed ADC saturation (in ADC samples)
	Tango::DevLong	interlockOverflowDuration;
	//	InterlockGainDependentThreshold:	Sets the threshold for gain dependent mode of Interlock 
	//  operation.
	Tango::DevLong	interlockGainDependentThreshold;

//	Attribute data members
public:
	Tango::DevLong	*attr_ExternalTriggerDelay_read;
	Tango::DevLong	*attr_PMOffset_read;
	Tango::DevBoolean	*attr_PMNotified_read;
	Tango::DevBoolean	*attr_InterlockXNotified_read;
	Tango::DevBoolean	*attr_InterlockYNotified_read;
	Tango::DevBoolean	*attr_InterlockAttnNotified_read;
	Tango::DevBoolean	*attr_InterlockADCPreFilterNotified_read;
	Tango::DevBoolean	*attr_InterlockADCPostFilterNotified_read;
	Tango::DevDouble	*attr_InterlockLimitXMin_read;
	Tango::DevDouble	*attr_InterlockLimitXMax_read;
	Tango::DevDouble	*attr_InterlockLimitYMin_read;
	Tango::DevDouble	*attr_InterlockLimitYMax_read;
	Tango::DevBoolean	*attr_ConditionSwitching_read;
	Tango::DevBoolean	*attr_ExternalSwitching_read;
	Tango::DevLong	*attr_SwitchingDelay_read;
	Tango::DevShort	*attr_DSCMode_read;
	Tango::DevBoolean	*attr_AGCEnabled_read;
	Tango::DevDouble	*attr_Gain_read;
	Tango::DevLong	*attr_TimePhase_read;
	Tango::DevBoolean	*attr_InterlockEnabled_read;
	Tango::DevBoolean	*attr_InterlockGainDependentEnabled_read;
	Tango::DevLong	*attr_InterlockOverflowThreshold_read;
	Tango::DevLong	*attr_InterlockOverflowDuration_read;
	Tango::DevLong	*attr_InterlockGainDependentThreshold_read;
	Tango::DevDouble	*attr_Kx_read;
	Tango::DevDouble	*attr_Ky_read;
	Tango::DevDouble	*attr_XOffset_read;
	Tango::DevDouble	*attr_YOffset_read;
	Tango::DevBoolean	*attr_TDEnabled_read;
	Tango::DevLong	*attr_TDBufferSize_read;
	Tango::DevUShort	*attr_TDDecimationFactor_read;
	Tango::DevLong	*attr_TDTriggerOffset_read;
	Tango::DevBoolean	*attr_TDBufferFreezingEnabled_read;
	Tango::DevBoolean	*attr_TDBufferFrozen_read;
	Tango::DevLong	*attr_TDTriggerCounter_read;
	Tango::DevDouble	*attr_Ks_read;
	Tango::DevDouble	*attr_QOffset_read;
	Tango::DevDouble	*attr_SOffset_read;
	Tango::DevShort	*attr_SynchronizationStatus_read;
	Tango::DevLong	*attr_MaxADC_read;
	Tango::DevLong	*attr_SPThreshold_read;
	Tango::DevLong	*attr_SPnBefore_read;
	Tango::DevLong	*attr_SPnAfter_read;
	Tango::DevLong	*attr_PMBufferSize_read;
	Tango::DevShort	*attr_PMSource_read;
	Tango::DevLong	*attr_SynchronizeLMT_read;
	Tango::DevLong	*attr_InterlockFilterOverflow_read;
	Tango::DevLong	*attr_InterlockFilterPosition_read;
	Tango::DevShort	*attr_UserData_read;
	Tango::DevString	*attr_logs_read;
	Tango::DevDouble	*attr_XPosTD_read;
	Tango::DevDouble	*attr_YPosTD_read;
	Tango::DevDouble	*attr_QuadTD_read;
	Tango::DevDouble	*attr_SumTD_read;
	Tango::DevDouble	*attr_VaTD_read;
	Tango::DevDouble	*attr_VbTD_read;
	Tango::DevDouble	*attr_VcTD_read;
	Tango::DevDouble	*attr_VdTD_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	LiberaBrilliancePlus(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	LiberaBrilliancePlus(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	LiberaBrilliancePlus(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~LiberaBrilliancePlus() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : LiberaBrilliancePlus::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : LiberaBrilliancePlus::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute ExternalTriggerDelay related methods
 *	Description: Sets the delay on the external trigger arrival. 
 *               The delay is set in steps of ADC samples (~ 9 ns).
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_ExternalTriggerDelay(Tango::Attribute &attr);
	virtual void write_ExternalTriggerDelay(Tango::WAttribute &attr);
	virtual bool is_ExternalTriggerDelay_allowed(Tango::AttReqType type);
/**
 *	Attribute PMOffset related methods
 *	Description: Offset relative to the post mortem event setting. 
 *               Set value is in turns, e.g. 1024 would mean that post mortem 
 *               acquisition is starting 1024 turns after the post mortem trigger 
 *               was received.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_PMOffset(Tango::Attribute &attr);
	virtual void write_PMOffset(Tango::WAttribute &attr);
	virtual bool is_PMOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute PMNotified related methods
 *	Description: Post Moterm notification flag
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_PMNotified(Tango::Attribute &attr);
	virtual void write_PMNotified(Tango::WAttribute &attr);
	virtual bool is_PMNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockXNotified related methods
 *	Description: Sets to 1 if X position trip caused the Interlock event.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockXNotified(Tango::Attribute &attr);
	virtual bool is_InterlockXNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockYNotified related methods
 *	Description: Sets to 1 if Yposition trip caused the Interlock event.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockYNotified(Tango::Attribute &attr);
	virtual bool is_InterlockYNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockAttnNotified related methods
 *	Description: Sets to 1 if the attenuator's value is higher than gain 
 *               dependence threshold
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockAttnNotified(Tango::Attribute &attr);
	virtual bool is_InterlockAttnNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockADCPreFilterNotified related methods
 *	Description: ADC overflow without filtering.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockADCPreFilterNotified(Tango::Attribute &attr);
	virtual bool is_InterlockADCPreFilterNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockADCPostFilterNotified related methods
 *	Description: ADC overflow with filtering.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockADCPostFilterNotified(Tango::Attribute &attr);
	virtual bool is_InterlockADCPostFilterNotified_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockLimitXMin related methods
 *	Description: Lower limit of the X position interlock threshold in mm (Writable only via Property)
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_InterlockLimitXMin(Tango::Attribute &attr);
	virtual bool is_InterlockLimitXMin_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockLimitXMax related methods
 *	Description: Upper limit of the X position interlock threshold in mm (Writable only via Property)
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_InterlockLimitXMax(Tango::Attribute &attr);
	virtual bool is_InterlockLimitXMax_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockLimitYMin related methods
 *	Description: Lower limit of the Y position interlock threshold in mm (Writable only via Property)
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_InterlockLimitYMin(Tango::Attribute &attr);
	virtual bool is_InterlockLimitYMin_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockLimitYMax related methods
 *	Description: Upper limit of the Y position interlock threshold in mm (Writable only via Property)
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_InterlockLimitYMax(Tango::Attribute &attr);
	virtual bool is_InterlockLimitYMax_allowed(Tango::AttReqType type);
/**
 *	Attribute ConditionSwitching related methods
 *	Description: Enables / disables the switching mechanism.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_ConditionSwitching(Tango::Attribute &attr);
	virtual void write_ConditionSwitching(Tango::WAttribute &attr);
	virtual bool is_ConditionSwitching_allowed(Tango::AttReqType type);
/**
 *	Attribute ExternalSwitching related methods
 *	Description: Sets the source of switching clock MC (external) or from the 
 *               oscillator (internal). Default value is internal.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_ExternalSwitching(Tango::Attribute &attr);
	virtual void write_ExternalSwitching(Tango::WAttribute &attr);
	virtual bool is_ExternalSwitching_allowed(Tango::AttReqType type);
/**
 *	Attribute SwitchingDelay related methods
 *	Description: Sets the delay of the switch position change relative to the 
 *               switching source clock.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SwitchingDelay(Tango::Attribute &attr);
	virtual void write_SwitchingDelay(Tango::WAttribute &attr);
	virtual bool is_SwitchingDelay_allowed(Tango::AttReqType type);
/**
 *	Attribute DSCMode related methods
 *	Description: Sets the adjustment (learning) of the amplitude and phase coefficients true or false. Set the coefficients type, adjusted or unity. Combination of these two nodes is necessary to achieve backward compatiblity.
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Scalar
 */
	virtual void read_DSCMode(Tango::Attribute &attr);
	virtual void write_DSCMode(Tango::WAttribute &attr);
	virtual bool is_DSCMode_allowed(Tango::AttReqType type);
/**
 *	Attribute AGCEnabled related methods
 *	Description: Enables/disables the Automatic Gain Control
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_AGCEnabled(Tango::Attribute &attr);
	virtual void write_AGCEnabled(Tango::WAttribute &attr);
	virtual bool is_AGCEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute Gain related methods
 *	Description: Sets the power_level. Attenuation at chosen level 
 *               depends on the gain scheme configuration. AGC 
 *               must be disabled to use manual Gain setting.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Gain(Tango::Attribute &attr);
	virtual void write_Gain(Tango::WAttribute &attr);
	virtual bool is_Gain_allowed(Tango::AttReqType type);
/**
 *	Attribute TimePhase related methods
 *	Description: The Machine Time Phase
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_TimePhase(Tango::Attribute &attr);
	virtual void write_TimePhase(Tango::WAttribute &attr);
	virtual bool is_TimePhase_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockEnabled related methods
 *	Description: Enables / disables the Interlock detection.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockEnabled(Tango::Attribute &attr);
	virtual void write_InterlockEnabled(Tango::WAttribute &attr);
	virtual bool is_InterlockEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockGainDependentEnabled related methods
 *	Description: Enables / disables gain dependent mode of Interlock operation.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_InterlockGainDependentEnabled(Tango::Attribute &attr);
	virtual void write_InterlockGainDependentEnabled(Tango::WAttribute &attr);
	virtual bool is_InterlockGainDependentEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockOverflowThreshold related methods
 *	Description: ADC saturation threshold.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_InterlockOverflowThreshold(Tango::Attribute &attr);
	virtual void write_InterlockOverflowThreshold(Tango::WAttribute &attr);
	virtual bool is_InterlockOverflowThreshold_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockOverflowDuration related methods
 *	Description: Duration of allowed ADC saturation (in ADC samples).
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_InterlockOverflowDuration(Tango::Attribute &attr);
	virtual void write_InterlockOverflowDuration(Tango::WAttribute &attr);
	virtual bool is_InterlockOverflowDuration_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockGainDependentThreshold related methods
 *	Description: Sets the threshold for gain dependent mode of Interlock 
 *               operation.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_InterlockGainDependentThreshold(Tango::Attribute &attr);
	virtual void write_InterlockGainDependentThreshold(Tango::WAttribute &attr);
	virtual bool is_InterlockGainDependentThreshold_allowed(Tango::AttReqType type);
/**
 *	Attribute Kx related methods
 *	Description: Sets the Kx for X position calculation. Default setting is 10 mm 
 *               (=10000000 nm).
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Kx(Tango::Attribute &attr);
	virtual void write_Kx(Tango::WAttribute &attr);
	virtual bool is_Kx_allowed(Tango::AttReqType type);
/**
 *	Attribute Ky related methods
 *	Description: Sets the Ky for Y position calculation. Default setting is 10 mm 
 *               (=10000000 nm).
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Ky(Tango::Attribute &attr);
	virtual void write_Ky(Tango::WAttribute &attr);
	virtual bool is_Ky_allowed(Tango::AttReqType type);
/**
 *	Attribute XOffset related methods
 *	Description: Sets the offset for X position in nm. Default value is 0 nm.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_XOffset(Tango::Attribute &attr);
	virtual void write_XOffset(Tango::WAttribute &attr);
	virtual bool is_XOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute YOffset related methods
 *	Description: Sets the offset for Y position in nm. Default value is 0 nm.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_YOffset(Tango::Attribute &attr);
	virtual void write_YOffset(Tango::WAttribute &attr);
	virtual bool is_YOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute TDEnabled related methods
 *	Description: TD data source activation flag
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_TDEnabled(Tango::Attribute &attr);
	virtual void write_TDEnabled(Tango::WAttribute &attr);
	virtual bool is_TDEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute TDBufferSize related methods
 *	Description: The number of samples to be read on TD data source.
 *               Influences the size of the associated attributes [such as XPosTD for instance].
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_TDBufferSize(Tango::Attribute &attr);
	virtual void write_TDBufferSize(Tango::WAttribute &attr);
	virtual bool is_TDBufferSize_allowed(Tango::AttReqType type);
/**
 *	Attribute TDDecimationFactor related methods
 *	Description: The TD decimation factor
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
	virtual void read_TDDecimationFactor(Tango::Attribute &attr);
	virtual void write_TDDecimationFactor(Tango::WAttribute &attr);
	virtual bool is_TDDecimationFactor_allowed(Tango::AttReqType type);
/**
 *	Attribute TDTriggerOffset related methods
 *	Description: TD data offset in num. of turns
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_TDTriggerOffset(Tango::Attribute &attr);
	virtual void write_TDTriggerOffset(Tango::WAttribute &attr);
	virtual bool is_TDTriggerOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute TDBufferFreezingEnabled related methods
 *	Description: TD buffer freezing activation flag
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_TDBufferFreezingEnabled(Tango::Attribute &attr);
	virtual bool is_TDBufferFreezingEnabled_allowed(Tango::AttReqType type);
/**
 *	Attribute TDBufferFrozen related methods
 *	Description: TD buffer status
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_TDBufferFrozen(Tango::Attribute &attr);
	virtual bool is_TDBufferFrozen_allowed(Tango::AttReqType type);
/**
 *	Attribute TDTriggerCounter related methods
 *	Description: Number of trigger notifications received since last device <init>
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_TDTriggerCounter(Tango::Attribute &attr);
	virtual bool is_TDTriggerCounter_allowed(Tango::AttReqType type);
/**
 *	Attribute Ks related methods
 *	Description: Coefficient for SUM value. Default setting is 67108864.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Ks(Tango::Attribute &attr);
	virtual void write_Ks(Tango::WAttribute &attr);
	virtual bool is_Ks_allowed(Tango::AttReqType type);
/**
 *	Attribute QOffset related methods
 *	Description: Sets the offset for Q position in nm. Default value is 0 nm.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_QOffset(Tango::Attribute &attr);
	virtual void write_QOffset(Tango::WAttribute &attr);
	virtual bool is_QOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute SOffset related methods
 *	Description: Coefficient for SUM value. Default setting is 67108864.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_SOffset(Tango::Attribute &attr);
	virtual void write_SOffset(Tango::WAttribute &attr);
	virtual bool is_SOffset_allowed(Tango::AttReqType type);
/**
 *	Attribute SynchronizationStatus related methods
 *	Description: Synchronization state machine enables the control application to easily monitor the synchronization state of all connected Libera Brilliance+.
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Scalar
 */
	virtual void read_SynchronizationStatus(Tango::Attribute &attr);
	virtual bool is_SynchronizationStatus_allowed(Tango::AttReqType type);
/**
 *	Attribute MaxADC related methods
 *	Description: The MAX ADC is monitored to assess the level of the input signal (ADC saturation). It can be reset on read or on trigger. [OnTrigger, OnRead]
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_MaxADC(Tango::Attribute &attr);
	virtual bool is_MaxADC_allowed(Tango::AttReqType type);
/**
 *	Attribute SPThreshold related methods
 *	Description: Specifies the threshold for start of calculation (in ADC counts) for the Single Pass functionality
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SPThreshold(Tango::Attribute &attr);
	virtual void write_SPThreshold(Tango::WAttribute &attr);
	virtual bool is_SPThreshold_allowed(Tango::AttReqType type);
/**
 *	Attribute SPnBefore related methods
 *	Description: specifies the number of samples to take before the threshold (in ADC samples) for the Single Pass functionality
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SPnBefore(Tango::Attribute &attr);
	virtual void write_SPnBefore(Tango::WAttribute &attr);
	virtual bool is_SPnBefore_allowed(Tango::AttReqType type);
/**
 *	Attribute SPnAfter related methods
 *	Description: specifies the number of samples to take after the threshold (in ADC samples) for the Single Pass functionality
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SPnAfter(Tango::Attribute &attr);
	virtual void write_SPnAfter(Tango::WAttribute &attr);
	virtual bool is_SPnAfter_allowed(Tango::AttReqType type);
/**
 *	Attribute PMBufferSize related methods
 *	Description: The number of samples to be read on PM data source.
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_PMBufferSize(Tango::Attribute &attr);
	virtual void write_PMBufferSize(Tango::WAttribute &attr);
	virtual bool is_PMBufferSize_allowed(Tango::AttReqType type);
/**
 *	Attribute PMSource related methods
 *	Description: source of the PM event external interlock limits
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Scalar
 */
	virtual void read_PMSource(Tango::Attribute &attr);
	virtual void write_PMSource(Tango::WAttribute &attr);
	virtual bool is_PMSource_allowed(Tango::AttReqType type);
/**
 *	Attribute SynchronizeLMT related methods
 *	Description: The absolute time synchronization is done for all processor modules simultaneously.  [0, 18446744073709551614]
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SynchronizeLMT(Tango::Attribute &attr);
	virtual void write_SynchronizeLMT(Tango::WAttribute &attr);
	virtual bool is_SynchronizeLMT_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockFilterOverflow related methods
 *	Description: boards.rafX.interlock.filter.overflow
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_InterlockFilterOverflow(Tango::Attribute &attr);
	virtual void write_InterlockFilterOverflow(Tango::WAttribute &attr);
	virtual bool is_InterlockFilterOverflow_allowed(Tango::AttReqType type);
/**
 *	Attribute InterlockFilterPosition related methods
 *	Description: boards.rafX.interlock.filter.position
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_InterlockFilterPosition(Tango::Attribute &attr);
	virtual void write_InterlockFilterPosition(Tango::WAttribute &attr);
	virtual bool is_InterlockFilterPosition_allowed(Tango::AttReqType type);
/**
 *	Attribute UserData related methods
 *	Description: User defined data
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Spectrum max = 256
 */
	virtual void read_UserData(Tango::Attribute &attr);
	virtual bool is_UserData_allowed(Tango::AttReqType type);
/**
 *	Attribute logs related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 2048
 */
	virtual void read_logs(Tango::Attribute &attr);
	virtual bool is_logs_allowed(Tango::AttReqType type);
/**
 *	Attribute XPosTD related methods
 *	Description: Turn by turn data: X Pos.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_XPosTD(Tango::Attribute &attr);
	virtual bool is_XPosTD_allowed(Tango::AttReqType type);
/**
 *	Attribute YPosTD related methods
 *	Description: Turn by turn data: Y Pos.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_YPosTD(Tango::Attribute &attr);
	virtual bool is_YPosTD_allowed(Tango::AttReqType type);
/**
 *	Attribute QuadTD related methods
 *	Description: Turn by turn data: Quad
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_QuadTD(Tango::Attribute &attr);
	virtual bool is_QuadTD_allowed(Tango::AttReqType type);
/**
 *	Attribute SumTD related methods
 *	Description: Turn by turn data: Sum
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_SumTD(Tango::Attribute &attr);
	virtual bool is_SumTD_allowed(Tango::AttReqType type);
/**
 *	Attribute VaTD related methods
 *	Description: Turn by turn data: Va
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_VaTD(Tango::Attribute &attr);
	virtual bool is_VaTD_allowed(Tango::AttReqType type);
/**
 *	Attribute VbTD related methods
 *	Description: Turn by turn data: Vb
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_VbTD(Tango::Attribute &attr);
	virtual bool is_VbTD_allowed(Tango::AttReqType type);
/**
 *	Attribute VcTD related methods
 *	Description: Turn by turn data: Vc
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_VcTD(Tango::Attribute &attr);
	virtual bool is_VcTD_allowed(Tango::AttReqType type);
/**
 *	Attribute VdTD related methods
 *	Description: Turn by turn data: Vd
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 250000
 */
	virtual void read_VdTD(Tango::Attribute &attr);
	virtual bool is_VdTD_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : LiberaBrilliancePlus::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command State related method
	 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
	 *
	 *	@returns State Code
	 */
	virtual Tango::DevState dev_state();
	/**
	 *	Command Status related method
	 *	Description: This command gets the device status (stored in its <i>device_status</i> data member) and returns it to the caller.
	 *
	 *	@returns Status description
	 */
	virtual Tango::ConstDevString dev_status();
	/**
	 *	Command GetParameters related method
	 *	Description: Retruns the current gains and offsets (i.e. the parameters used for position computation)
	 *
	 *	@returns The BPM gain and offsets
	 */
	virtual Tango::DevVarDoubleStringArray *get_parameters();
	virtual bool is_GetParameters_allowed(const CORBA::Any &any);
	/**
	 *	Command ResetPMNotification related method
	 *	Description: 
	 *
	 */
	virtual void reset_pmnotification();
	virtual bool is_ResetPMNotification_allowed(const CORBA::Any &any);
	/**
	 *	Command ResetInterlockNotification related method
	 *	Description: Resets the interlock notification flags to false
	 *
	 */
	virtual void reset_interlock_notification();
	virtual bool is_ResetInterlockNotification_allowed(const CORBA::Any &any);
	/**
	 *	Command SetInterlockConfiguration related method
	 *	Description: Change interlock configuration using the InterlockConfiguration class (or device) property.
	 *               Only  modify  the interlock configuration, the remaining env. parameters remain unchanged.
	 *
	 */
	virtual void set_interlock_configuration();
	virtual bool is_SetInterlockConfiguration_allowed(const CORBA::Any &any);
	/**
	 *	Command SetTimeOnNextTrigger related method
	 *	Description: Applies both machine et system time values on next trigger
	 *
	 */
	virtual void set_time_on_next_trigger();
	virtual bool is_SetTimeOnNextTrigger_allowed(const CORBA::Any &any);
	/**
	 *	Command SaveDSCParameters related method
	 *	Description: Saves the current DSC parameters
	 *
	 */
	virtual void save_dscparameters();
	virtual bool is_SaveDSCParameters_allowed(const CORBA::Any &any);
	/**
	 *	Command ReloadSystemProperties related method
	 *	Description: 
	 *
	 */
	virtual void reload_system_properties();
	virtual bool is_ReloadSystemProperties_allowed(const CORBA::Any &any);
	/**
	 *	Command SetRefIncoherence related method
	 *	Description: Set the actual incoherence value as refeference value for the drift alarm calculation.
	 *
	 */
	virtual void set_ref_incoherence();
	virtual bool is_SetRefIncoherence_allowed(const CORBA::Any &any);
	/**
	 *	Command MagicCommand related method
	 *	Description: Directly dump the Libera ireg node structure. If the input argument is a sub tree all subnodes will be dumped out.
	 *
	 *	@param argin absolute path of the node name
	 *	@returns value of specified node(s)
	 */
	virtual Tango::DevVarStringArray *magic_command(Tango::DevString argin);
	virtual bool is_MagicCommand_allowed(const CORBA::Any &any);
	/**
	 *	Command EnableTDBufferFreezing related method
	 *	Description: Enables the TD buffer freezing mechanism
	 *
	 */
	virtual void enable_tdbuffer_freezing();
	virtual bool is_EnableTDBufferFreezing_allowed(const CORBA::Any &any);
	/**
	 *	Command DisableTDBufferFreezing related method
	 *	Description: Disables the TD buffer freezing mechanism
	 *
	 */
	virtual void disable_tdbuffer_freezing();
	virtual bool is_DisableTDBufferFreezing_allowed(const CORBA::Any &any);
	/**
	 *	Command EnableTD related method
	 *	Description: Enables the so called ``data on demand`` (i.e. first turns) data source
	 *
	 */
	virtual void enable_td();
	virtual bool is_EnableTD_allowed(const CORBA::Any &any);
	/**
	 *	Command DisableTD related method
	 *	Description: Disables the so called ``data on demand`` (i.e. first turns) data source
	 *
	 */
	virtual void disable_td();
	virtual bool is_DisableTD_allowed(const CORBA::Any &any);
	/**
	 *	Command UnfreezeTDBuffer related method
	 *	Description: Unfreezes the TD buffer
	 *
	 */
	virtual void unfreeze_tdbuffer();
	virtual bool is_UnfreezeTDBuffer_allowed(const CORBA::Any &any);
	/**
	 *	Command ForceInitSettings related method
	 *	Description: Initializing Libera Default Settings (Based to the properties) without performing init_device
	 *
	 */
	virtual void force_init_settings();
	virtual bool is_ForceInitSettings_allowed(const CORBA::Any &any);
	/**
	 *	Command SetTraceLevel related method
	 *	Description: Sets the Trace Error Level:  	Off     = 0,
	 *                       		Low     = 1,
	 *               		Med     = 2,
	 *               		High    = 3,
	 *               		Detail  = 4
	 *
	 *	@param argin 
	 */
	virtual void set_trace_level(Tango::DevUShort argin);
	virtual bool is_SetTraceLevel_allowed(const CORBA::Any &any);
	/**
	 *	Command DisableAllSignals related method
	 *	Description: Disables All the Signals.
	 *
	 */
	virtual void disable_all_signals();
	virtual bool is_DisableAllSignals_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : LiberaBrilliancePlus::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(LiberaBrilliancePlus::Additional Method prototypes) ENABLED START -----*/

	//	Additional Method prototypes
	void UpdatePM();
 
  void set_lib_error(std::string nodeinfo);

  std::string set_interlock_status();

/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::Additional Method prototypes
};

/*----- PROTECTED REGION ID(LiberaBrilliancePlus::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	LiberaBrilliancePlus::Additional Classes Definitions

}	//	End of namespace

#endif   //	LiberaBrilliancePlus_H
